# Generated by Django 5.2 on 2025-04-09 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
