# Generated by Django 5.2 on 2025-04-13 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0002_guide_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guide',
            name='email',
        ),
        migrations.RemoveField(
            model_name='guide',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='guide',
            name='last_name',
        ),
        migrations.AlterField(
            model_name='guide',
            name='bio',
            field=models.TextField(blank=True, default='Not Provided', null=True),
        ),
        migrations.AlterField(
            model_name='guide',
            name='experience',
            field=models.CharField(blank=True, choices=[('Amateur', 'Amateur'), ('Professional', 'Professional')], default='Amateur', max_length=20),
        ),
        migrations.AlterField(
            model_name='guide',
            name='phone_number',
            field=models.CharField(blank=True, default='Not Provided', max_length=20),
        ),
    ]
